# This YAML is used for the docfx v2 daily pre-release CI (https://dev.azure.com/ceapex/Engineering/_build?definitionId=1743&_a=summary)

pool:
  name: 1ES-Pool
  demands: ImageOverride -equals Win2019VS2019

variables:
- group: docfx-v2-pipeline-kv
- name: NUGETEXE
  value: nuget

steps:

- task: UseDotNet@2
  displayName: 'Install .NET Core SDK required for ESRPCodeSigning'
  inputs:
    packageType: sdk
    version: '2.1.811'

- task: UseDotNet@2
  displayName: 'Install .NET Core SDK required for docfx'
  inputs:
    packageType: sdk
    version: '5.0.100'

- task: NodeTool@0
  displayName: 'Use Node 8.x'
  inputs:
    versionSpec: 8.x

- task: NuGetToolInstaller@1
  displayName: 'Use NuGet'

- task: CmdLine@1
  displayName: 'npm install'
  inputs:
    filename: npm
    arguments: install
    workingFolder: tools/Deployment

- task: CmdLine@1
  displayName: 'tsc compile'
  inputs:
    filename: node
    arguments: '.\node_modules\typescript\bin\tsc'
    workingFolder: tools/Deployment

- task: CmdLine@1
  displayName: 'gulp build'
  inputs:
    filename: node
    arguments: '.\node_modules\gulp\bin\gulp.js dev:build'
    workingFolder: tools/Deployment

- task: UseDotNet@2
  displayName: 'Install .NET Core sdk required for ESRPCodeSigning'
  inputs:
    packageType: sdk
    version: '2.1.811'

- task: EsrpCodeSigning@1
  displayName: Sign docfx executables and dlls
  inputs:
    ConnectedServiceName: 'CodeSigning-APEX'
    FolderPath: '$(Build.SourcesDirectory)/target/Release'
    Pattern: |
        **\Microsoft.DocAsCode.*.dll
        **\*.exe
    UseMinimatch: true
    signConfigType: inlineSignParams
    inlineOperation: |
     [
        {
          "KeyCode": "CP-230012",
          "OperationSetCode": "SigntoolSign",
          "parameters": [
            {
              "parameterName": "OpusName",
              "parameterValue": "Microsoft"
            },
            {
              "parameterName": "OpusInfo",
              "parameterValue": "http://www.microsoft.com"
            },
            {
              "parameterName": "PageHash",
              "parameterValue": "/NPH"
            },
            {
              "parameterName": "TimeStamp",
              "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
            },
            {
              "parameterName": "FileDigest",
              "parameterValue": "/fd \"SHA256\""
            }
          ],
          "ToolName": "sign",
          "ToolVersion": "1.0"
        },
        {
          "KeyCode": "CP-230012",
          "OperationSetCode": "SigntoolVerify",
          "Parameters": [
            {
              "parameterName": "VerifyAll",
              "parameterValue": "/all"
            }
          ],
          "ToolName": "sign",
          "ToolVersion": "1.0"
        }
      ]
    SessionTimeout: '60'
    MaxConcurrency: '50'
    MaxRetryAttempts: '5'

- task: EsrpCodeSigning@1
  displayName: Sign dependent dlls
  inputs:
    ConnectedServiceName: 'CodeSigning-APEX'
    FolderPath: '$(Build.SourcesDirectory)/target/Release'
    Pattern: |
        **\*.dll
        !**\System.*.dll
        !**\Microsoft.!(DocAsCode).*.dll
        !**\NuGet.*.dll
        !**\FSharp.Core.*.dll
    UseMinimatch: true
    signConfigType: inlineSignParams
    inlineOperation: |
     [
        {
          "KeyCode": "CP-231522",
          "OperationSetCode": "SigntoolSign",
          "parameters": [
            {
              "parameterName": "OpusName",
              "parameterValue": "Microsoft"
            },
            {
              "parameterName": "OpusInfo",
              "parameterValue": "http://www.microsoft.com"
            },
            {
              "parameterName": "Append",
              "parameterValue": "/as"
            },
            {
              "parameterName": "PageHash",
              "parameterValue": "/NPH"
            },
            {
              "parameterName": "TimeStamp",
              "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
            },
            {
              "parameterName": "FileDigest",
              "parameterValue": "/fd \"SHA256\""
            }
          ],
          "ToolName": "sign",
          "ToolVersion": "1.0"
        },
        {
          "KeyCode": "CP-231522",
          "OperationSetCode": "SigntoolVerify",
          "Parameters": [
            {
              "parameterName": "VerifyAll",
              "parameterValue": "/all"
            }
          ],
          "ToolName": "sign",
          "ToolVersion": "1.0"
        }
      ]
    SessionTimeout: '60'
    MaxConcurrency: '50'
    MaxRetryAttempts: '5'

- task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
  displayName: 'Component Detection'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

- task: CmdLine@1
  displayName: 'gulp pack'
  inputs:
    filename: node
    arguments: '.\node_modules\gulp\bin\gulp.js dev:release'
    workingFolder: tools/Deployment
  env:
    AZDEVOPSPAT: $(AzureDevOpsFeedPAT)

- task: PublishBuildArtifacts@1
  condition: always()
  inputs:
    pathtoPublish: 'target\Release\docfx'
    artifactName: target

- task: PublishBuildArtifacts@1
  condition: always()
  inputs:
    pathtoPublish: 'test\docfx-seed\_site'
    artifactName: docfx-seed-site